### ISSUE TITLE
关于联名卡链接获取的问题

### ISSUE THREAD

**Issue by zhengqingqian** [tenpiece/weread_helper_extension#14]
联名卡集赞如何获取点赞链接啊

**Comment by ghysrc** [comment]
@zhengqingqian 你找到办法了吗？我发现这个插件，看见提交链接也是莫名其妙的，手机和电脑上都试了下，折腾不出链接来

**Comment by zhengqingqian** [comment]
> @zhengqingqian 你找到办法了吗？我发现这个插件，看见提交链接也是莫名其妙的，手机和电脑上都试了下，折腾不出链接来

没有啊，那个链接我也不知道怎么得到，哭

**Comment by ghysrc** [comment]
@zhengqingqian 我今天又搜了一下，最终还是找到了。在这篇文章里面有，每次只要替换vid和日期就行了。
https://mp.weixin.qq.com/s/TUNM8L1ROrgz2BARlXQ20w

**Comment by zhengqingqian** [comment]
> @zhengqingqian 我今天又搜了一下，最终还是找到了。在这篇文章里面有，每次只要替换vid和日期就行了。
> https://mp.weixin.qq.com/s/TUNM8L1ROrgz2BARlXQ20w

哇，可以可以，感谢

**Comment by yejingxin** [comment]
能不能提一个查询接口？输入vid，就能查询到链接是否提交成功，以及自己在queue的位置
