### ISSUE TITLE
微信扫码提示 请到微信读书APP参与活动

### ISSUE THREAD

**Issue by chenweil** [tenpiece/weread_helper_extension#46]
## 微信扫码中，页面无法点击跳转微信读书的按钮
 请到微信读书APP参与活动 这个按钮。 是不是已经默认关闭这种操作方式了？
大家知道怎么搞吗？

**Comment by bcllemon** [comment]
+1,估计是改了玩法吧

**Comment by chenweil** [comment]
> +1,估计是改了玩法吧

是吧？我不知道怎么通过微信读书去加入这些组队。

现在感觉读书的口子进一步缩紧了。

估计要找个群来组队的节奏了。

**Comment by key22999** [comment]
+1進不去

**Comment by pumpbumb** [comment]
> +1,估计是改了玩法吧

腾讯的一贯做法😂

**Comment by GF521123** [comment]
有建群的不？

**Comment by si-wusu** [comment]
但是为什么有些人还可以

**Comment by huangzf128** [comment]
最近好像是被TX给封了.

**Comment by chenweil** [comment]
有小程序了，可以用那个组队。瓦斯助手

**Comment by chenweil** [comment]
小程序 瓦斯助手
